#./Dockerfile
FROM rocker/rstudio

LABEL   authors ="Jyotirmoy Das" \
        description = "Docker image containing all requirement for the AlveolarCellTypeDeconvolution pipeline"

RUN apt-get update \
        && apt-get install -y --no-install-recommends apt-utils \
        && apt-get install -y --no-install-recommends \
        ## Basic deps
        gdb \
        python3-pip \
        libz-dev \
        liblzma-dev \
        libbz2-dev \
        libpng-dev \
        libgit2-dev \
        ## sys deps from bioc_full
        pkg-config \
        fortran77-compiler \
        byacc \
        automake \
        curl \
        ## This section installs libraries
        libpcre2-dev \
        libnetcdf-dev \
        libhdf5-serial-dev \
        libfftw3-dev \
        libopenbabel-dev \
        libopenmpi-dev \
        libxt-dev \
        libudunits2-dev \
        libgeos-dev \
        libproj-dev \
        libtiff5-dev \
        libreadline-dev \
        libgsl0-dev \
        libgslcblas0 \
        libgtk2.0-dev \
        libgl1-mesa-dev \
        libglu1-mesa-dev \
        libgmp3-dev \
        libhdf5-dev \
        libncurses-dev \
        libbz2-dev \
        libxpm-dev \
        liblapack-dev \
        libv8-dev \
        libgtkmm-2.4-dev \
        libmpfr-dev \
        libmodule-build-perl \
        libapparmor-dev \
        libprotoc-dev \
        librdf0-dev \
        libmagick++-dev \
        libsasl2-dev \
        libpoppler-cpp-dev \
        libprotobuf-dev \
        libpq-dev \
        libperl-dev \
        libxml2-dev \
        libcairo2-dev \
        libsqlite3-dev \
        libmariadbd-dev \
        libssh2-1-dev \
        unixodbc-dev \
        libcurl4-openssl-dev \
        libssl-dev \
        zlib1g-dev \
        autoconf \
        git \
        wget \
        ## software - perl extensions and modules
        libarchive-extract-perl \
        libfile-copy-recursive-perl \
        libcgi-pm-perl \
        libdbi-perl \
        libdbd-mysql-perl \
        libxml-simple-perl \
        libmysqlclient-dev \
        default-libmysqlclient-dev \
        libgdal-dev \
        ## new libs
        libglpk-dev \
        ## Databases and other software
        sqlite \
        openmpi-bin \
        mpi-default-bin \
        openmpi-common \
        openmpi-doc \
        tcl8.6-dev \
        tk-dev \
        default-jdk \
        imagemagick \
        tabix \
        ggobi \
        graphviz \
        protobuf-compiler \
        jags \
        ## Additional resources
        xfonts-100dpi \
        xfonts-75dpi \
        biber \
        libsbml5-dev \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*

RUN apt-get update -qq && apt-get -y --no-install-recommends install \

    
## update system libraries
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get clean

## install R CRAN binary packages
RUN install2.r -e \
testthat

## Install remaining packages from source
COPY ./required-CRANlibraries.R .
RUN Rscript required-CRANlibraries.R

## Install Bioconductor packages
COPY ./required-BIOClibraries.R .
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
   libfftw3-dev \
   gcc && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
RUN Rscript -e 'requireNamespace("BiocManager"); BiocManager::install(ask=F);' \
&& Rscript requirements-bioc.R

# install the package
RUN git clone https://github.com/JD2112/AlveolarCellTypeDeconvolution.git && \
    cd AlveolarCellTypeDeconvolution && \
