theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://github.com/JD2112/AlveolarCellTypeDeconvolution/archive/refs/tags/v1.4.1.zip
  tar_url: https://github.com/JD2112/AlveolarCellTypeDeconvolution/archive/refs/tags/v1.4.1.tar.gz
